{% set name = "zppy" %}
{% set version = "2.3.0rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/E3SM-Project/zppy/archive/v{{ version }}.tar.gz
  sha256: 5c2d5976902735da378c0322cedb8b4a6d1940f75b72e151b0e9baa952e2c0c9

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python
  entry_points:
    - zppy = zppy.__main__:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - configobj >=5.0.0,<6.0.0
    - jinja2 >=2.0.0
    - mache >=1.3.2
    - mpas_tools >=0.15.0

test:
  requires:
    - pip
  imports:
    - zppy
  commands:
    - zppy --help
    - pip check

about:
  home: https://github.com/E3SM-Project/zppy
  summary: 'E3SM post-processing toolchain'
  license: BSD-3-Clause AND custom
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - mahf708
    - xylar
    - tomvothecoder
    - forsyth2
    - chengzhuzhang
